//DEPRECATED

module.exports.heroNamebyID = function(id){
  const heroIDName = []
  heroIDName[1] = 'Anti-Mage';
  heroIDName[2] = 'Axe';
  heroIDName[3] = 'Bane';
  heroIDName[4] = 'BloodSeeker';
  heroIDName[5] = 'Crystal Maiden';
  heroIDName[6] = 'Drow Ranger';
  heroIDName[7] = 'Earthshaker';
  heroIDName[8] = 'Juggernaut';
  heroIDName[9] = 'Mirana';
  heroIDName[10] = 'Morphling';
  heroIDName[11] = 'Shadow Fiend';
  heroIDName[12] = 'Phantom Lancer';
  heroIDName[13] = 'Puck';
  heroIDName[14] = 'Pudge';
  heroIDName[15] = 'Razor';
  heroIDName[16] = 'Sand King';
  heroIDName[17] = 'Storm Spirit';
  heroIDName[18] = 'Sven';
  heroIDName[19] = 'Tiny';
  heroIDName[20] = 'Vengeful Spirit';
  heroIDName[21] = 'Windranger';
  heroIDName[22] = 'Zeus';
  heroIDName[23] = 'Kunkka';
  heroIDName[24] = '';
  heroIDName[25] = 'Lina';
  heroIDName[26] = 'Lion';
  heroIDName[27] = 'Shadow Shaman';
  heroIDName[28] = 'Slardar';
  heroIDName[29] = 'Tidehunter';
  heroIDName[30] = 'Witch Doctor';
  heroIDName[31] = 'Lich';
  heroIDName[32] = 'Riki';
  heroIDName[33] = 'Enigma';
  heroIDName[34] = 'Tinker';
  heroIDName[35] = 'Sniper';
  heroIDName[36] = 'Necrophos';
  heroIDName[37] = 'Warlock';
  heroIDName[38] = 'Beastmaster';
  heroIDName[39] = 'Queen of Pain';
  heroIDName[40] = 'Venomancer';
  heroIDName[41] = 'Faceless Void';
  heroIDName[42] = 'Wraith King';
  heroIDName[43] = 'Death Prophet';
  heroIDName[44] = 'Phantom Assassin';
  heroIDName[45] = 'Pugna';
  heroIDName[46] = 'Templar Assassin';
  heroIDName[47] = 'Viper';
  heroIDName[48] = 'Luna';
  heroIDName[49] = 'Dragon Knight';
  heroIDName[50] = 'Dazzle';
  heroIDName[51] = 'Clockwerk';
  heroIDName[52] = 'Leshrac';
  heroIDName[53] = "Nature's Prophet";
  heroIDName[54] = 'Lifestealer';
  heroIDName[55] = 'Dark Seer';
  heroIDName[56] = 'Clinkz';
  heroIDName[57] = 'Omniknight';
  heroIDName[58] = 'Enchantress';
  heroIDName[59] = 'Huskar';
  heroIDName[60] = 'Night Stalker';
  heroIDName[61] = 'Broodmother';
  heroIDName[62] = 'Bounty Hunter';
  heroIDName[63] = 'Weaver';
  heroIDName[64] = 'Jakiro';
  heroIDName[65] = 'Batrider';
  heroIDName[66] = 'Chen';
  heroIDName[67] = 'Spectre';
  heroIDName[68] = 'Ancient Apparition';
  heroIDName[69] = 'Doom';
  heroIDName[70] = 'Ursa';
  heroIDName[71] = 'Spirit Breaker';
  heroIDName[72] = 'Gyrocopter';
  heroIDName[73] = 'Alchemist';
  heroIDName[74] = 'Invoker';
  heroIDName[75] = 'Silencer';
  heroIDName[76] = 'Outworld Devourer';
  heroIDName[77] = 'Lycanthrope';
  heroIDName[78] = 'Brewmaster';
  heroIDName[79] = 'Shadow Demon';
  heroIDName[80] = 'Lone Druid';
  heroIDName[81] = 'Chaos Knight';
  heroIDName[82] = 'Meepo';
  heroIDName[83] = 'Treant Protector';
  heroIDName[84] = 'Ogre Magi';
  heroIDName[85] = 'Undying';
  heroIDName[86] = 'Rubick';
  heroIDName[87] = 'Disruptor';
  heroIDName[88] = 'Nyx Assassin';
  heroIDName[89] = 'Naga Siren';
  heroIDName[90] = 'Keeper of the Light';
  heroIDName[91] = 'Wisp';
  heroIDName[92] = 'Visage';
  heroIDName[93] = 'Slark';
  heroIDName[94] = 'Medusa';
  heroIDName[95] = 'Troll Warlord';
  heroIDName[96] = 'Centaur Warrunner';
  heroIDName[97] = 'Magnus';
  heroIDName[98] = 'Timbersaw';
  heroIDName[99] = 'Bristleback';
  heroIDName[100] = 'Tusk';
  heroIDName[101] = 'Skywrath Mage';
  heroIDName[102] = 'Abaddon';
  heroIDName[103] = 'Elder Titan';
  heroIDName[104] = 'Legion Commander';
  heroIDName[105] = 'Techies';
  heroIDName[106] = 'Ember Spirit';
  heroIDName[107] = 'Earth Spirit';
  heroIDName[108] = 'Abyssal Underlord';
  heroIDName[109] = 'Terrorblade';
  heroIDName[110] = 'Phoenix';
  heroIDName[111] = 'Oracle';
  heroIDName[112] = 'Winter Wyvern';
  heroIDName[113] = 'Arc Warden';
  heroIDName[114] = 'Monkey King';
  heroIDName[115] = '';
  heroIDName[116] = '';
  heroIDName[117] = '';
  heroIDName[118] = '';
  heroIDName[119] = 'Dark Willow';
  heroIDName[120] = 'Pangolier';
  return heroIDName[parseInt(id)];
}

module.exports.gameModebyID = function(id){
  const gameMode = []
  gameMode[0] = 'Unknown';
  gameMode[1] = 'All Pick';
  gameMode[2] = "Captain's Mode";
  gameMode[3] = 'Random Draft';
  gameMode[4] = 'Single Draft';
  gameMode[5] = 'All Random';
  gameMode[6]	= 'Intro';
  gameMode[7]	= 'Diretide';
  gameMode[8]	= 'Reverse Captain’s Mode';
  gameMode[9]	= 'The Greeviling';
  gameMode[10] = 'Tutorial';
  gameMode[11] = 'Mid Only';
  gameMode[12] = 'Least Played';
  gameMode[13] = 'New Player Pool';
  gameMode[14] = 'Compendium Matchmaking';
  gameMode[15] = 'Custom';
  gameMode[16] = 'Captains Draft';
  gameMode[17] = 'Balanced Draft';
  gameMode[18] = 'Ability Draft';
  gameMode[19] = 'Event (?)';
  gameMode[20] = 'All Random Death Match';
  gameMode[21] = 'Solo Mid 1 vs 1';
  gameMode[22] = 'Ranked All Pick';
  gameMode[23] = 'Turbo';
  return gameMode[parseInt(id)]
}

module.exports.lobbyTypebyID = function(id){
  const lobbyType = [];
  lobbyType[-1] = 'Invalid';
  lobbyType[0] = 'Pública'; //Public matchmaking
  lobbyType[1] = 'Practica';
  lobbyType[2] = 'Torneo';
  lobbyType[3] = 'Tutorial';
  lobbyType[4] = 'Co-op co IA';
  lobbyType[5] = 'Partida de equipo';
  lobbyType[6] = 'Solo cola';
  lobbyType[7] = 'Ranked'; //Ranked matchmaking
  lobbyType[8] = 'Solo Mid 1 vs 1';
  return lobbyType[parseInt(id)]
}

module.exports.skillbyID = function(id){
  if(id == null){return ''}
  const skill = [];
  skill[0] = "Any";
  skill[1] = "Normal";
  skill[2] = "High";
  skill[3] = "Very High";
  return skill[parseInt(id)]
}

// TODO exportar como funciones o crear type para conseguir por id o nombre
