const { Command } = require('aghanim')
const basic = require('../helpers/basic')
const lang = require('../lang.json')

module.exports = new Command('getstarted-es',{
  category : 'General', help : 'Configuración de servidor', args : ''},
  function(msg, args, command){
    msg.reply(':flag_es: __**GUÍA DE SERVIDOR**__\n\n:small_blue_diamond: __**Requisitos**__\nPara la administración de las opciones del servidor es necesario crear un rol llamado **Aegis** y que los usuari@s administradores/as del servidor posean este rol para que puedan realizar las configuraciones de Roshan.\n\n:small_blue_diamond: __**Funcionalidades**__\n:white_small_square: **feeds**: tweets de cuentas específicas (configurable)\n:white_small_square: **notificaciones** importantes sobre el bot.\n:white_small_square: **borrar mensajes** con el comando `r!del [numero mensajes]` - máximo mensajes 100\n:white_small_square: posibilidad de **anclar/desanclar mensajes** reaccionando con :pin: (requiere además que Roshan tenga permisos de **administrar mensajes**)\n:white_small_square: **giveaways** `r!giveaway [roles]`\n\n__**Comando de ayuda**__: `r!help server`\n\n:small_blue_diamond: __**Configuración del servidor**__\n\n`r!server config` - muestra información sobre el servidor y su configuración.\n\n:small_blue_diamond: __**Configuración de Notificaciones**__\n`r!server notifications on/off` - activa/desactiva las notificaciones\n`r!server notifications [mención canal]` - configura al canal mencionado para recibir las notificaciones\n\n:small_blue_diamond: __**Configuración de Feeds**__\nActivar/desactivar y el canal funciona como `r!server notifications` solo que es `feeds` en vez de `notifications`\n`r!server sub <nombre de fuentes separadas por ,>` - se subscribe a las fuentes deseadas\n`r!server unsub <nombre de fuentes separadas por ,>` - se desubscribe a las fuentes deseadas\n`r!server subscriptions` - ve las fuentes disponibles para recibir feeds.\n\n:information_source: Por defecto, las notificaciones y feeds estarán activados en el canal por defecto del servidor.\n\n:small_blue_diamond: __**Más ayuda**__\n\nSi necesitas más ayuda, ven a mi servidor https://discord.gg/SxsYkgX')
  })
